/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check (process uniquement) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil de l’utilisateur courant */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Met à jour les préférences (jour de courses) */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée un compte et renvoie une paire de tokens */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un utilisateur */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renouvelle la paire de tokens */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recherche dans le catalogue d’ingrédients */
        get: operations["IngredientsController_search"];
        put?: never;
        /** Ajoute un ingrédient au catalogue */
        post: operations["IngredientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste paginée du catalogue de repas (filtres favorite/tag/name) */
        get: operations["MealsController_findAll"];
        put?: never;
        /** Crée un repas (admin uniquement) */
        post: operations["MealsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d’un repas (avec ingrédients) */
        get: operations["MealsController_findOne"];
        put?: never;
        post?: never;
        /** Supprime un repas (admin uniquement) */
        delete: operations["MealsController_remove"];
        options?: never;
        head?: never;
        /** Met à jour un repas (admin uniquement) */
        patch: operations["MealsController_update"];
        trace?: never;
    };
    "/meals/{id}/cooked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marque un repas comme cuisiné */
        post: operations["MealsController_markCooked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan courant de l’utilisateur, créé vide au premier accès */
        get: operations["PlanController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remplit les créneaux vides par tirage pondéré */
        post: operations["PlanController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Met à jour un créneau (repas / portions) */
        patch: operations["PlanController_updateSlot"];
        trace?: never;
    };
    "/plan/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Vide les créneaux du plan et les items dérivés de la liste (les items manuels sont conservés) */
        delete: operations["PlanController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste de courses matérialisée du plan (init paresseuse) */
        get: operations["ShoppingListController_forPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resynchronise les items dérivés depuis les plats */
        post: operations["ShoppingListController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ajoute un item manuel à la liste */
        post: operations["ShoppingListController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprime un item de la liste */
        delete: operations["ShoppingListController_removeItem"];
        options?: never;
        head?: never;
        /** Met à jour un item (checked, nom, quantité, unité) */
        patch: operations["ShoppingListController_updateItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            shoppingDay: number;
        };
        UpdateMeDto: {
            /** @description Jour de courses (0 = dimanche … 6 = samedi). */
            shoppingDay: number;
        };
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        Ingredient: {
            id: string;
            name: string;
            defaultUnit: string | null;
        };
        CreateIngredientDto: {
            name: string;
            defaultUnit?: string | null;
        };
        MealSummaryDto: {
            id: string;
            name: string;
            rating: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            lastCookedAt: string | null;
            timesCooked: number;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedMealsDto: {
            items: components["schemas"]["MealSummaryDto"][];
            total: number;
            page: number;
            limit: number;
        };
        MealIngredientDto: {
            ingredientId: string;
            quantity: number;
            unit: string;
        };
        CreateMealDto: {
            name: string;
            rating?: number;
            isFavorite?: boolean;
            tags?: string[];
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        MealIngredient: {
            id: string;
            ingredient: components["schemas"]["Ingredient"];
            ingredientId: string;
            quantity: number;
            unit: string;
        };
        Meal: {
            id: string;
            name: string;
            rating: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            lastCookedAt: string | null;
            timesCooked: number;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            ingredients: components["schemas"]["MealIngredient"][];
        };
        UpdateMealDto: {
            name?: string;
            rating?: number;
            isFavorite?: boolean;
            tags?: string[];
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        PlanSlotDto: {
            id: string;
            /** @description Rang du jour dans le plan : 0 = premier jour. */
            dayIndex: number;
            /** @enum {string} */
            slot: "LUNCH" | "DINNER";
            mealId: string | null;
            meal: components["schemas"]["MealSummaryDto"] | null;
            servings: number;
        };
        PlanDto: {
            id: string;
            /** @description Premier jour du plan (YYYY-MM-DD). Ancre d’affichage : sert à libeller les jours et à situer le jour courant, jamais à retrouver un plan. */
            startDate: string;
            /** @description Nombre de jours couverts par le plan. */
            dayCount: number;
            /** Format: date-time */
            createdAt: string;
            slots: components["schemas"]["PlanSlotDto"][];
        };
        UpdateSlotDto: {
            /** @description Repas à assigner, ou null pour vider le créneau */
            mealId?: string | null;
            servings?: number;
        };
        ShoppingListItemDto: {
            id: string;
            /** @enum {string} */
            source: "DERIVED" | "MANUAL";
            ingredientId: string | null;
            name: string;
            unit: string | null;
            quantity: number | null;
            checked: boolean;
        };
        ShoppingListDto: {
            planId: string;
            /** @description Premier jour du plan (YYYY-MM-DD) */
            startDate: string;
            items: components["schemas"]["ShoppingListItemDto"][];
        };
        CreateShoppingListItemDto: {
            name: string;
            quantity?: number;
            unit?: string;
        };
        UpdateShoppingListItemDto: {
            checked?: boolean;
            name?: string;
            quantity?: number;
            unit?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    IngredientsController_search: {
        parameters: {
            query?: {
                /** @description Filtre par nom (ILike) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    IngredientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    MealsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                favorite?: boolean;
                /** @description Filtre par tag exact */
                tag?: string;
                /** @description Filtre par nom (ILike) */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMealsDto"];
                };
            };
        };
    };
    MealsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMealDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MealsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_markCooked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    PlanController_find: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_updateSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSlotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    ShoppingListController_forPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShoppingListItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItemDto"];
                };
            };
        };
    };
    ShoppingListController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShoppingListController_updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShoppingListItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItemDto"];
                };
            };
        };
    };
}
