/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée un compte et renvoie une paire de tokens */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un utilisateur */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renouvelle la paire de tokens */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recherche dans le catalogue d’ingrédients */
        get: operations["IngredientsController_search"];
        put?: never;
        /** Ajoute un ingrédient au catalogue */
        post: operations["IngredientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste paginée des repas (filtres favorite/tag/name) */
        get: operations["MealsController_findAll"];
        put?: never;
        /** Crée un repas */
        post: operations["MealsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d’un repas (avec ingrédients) */
        get: operations["MealsController_findOne"];
        put?: never;
        post?: never;
        /** Supprime un repas */
        delete: operations["MealsController_remove"];
        options?: never;
        head?: never;
        /** Met à jour un repas */
        patch: operations["MealsController_update"];
        trace?: never;
    };
    "/meals/{id}/cooked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marque un repas comme cuisiné */
        post: operations["MealsController_markCooked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weeks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semaine courante de l’utilisateur */
        get: operations["WeeksController_findCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée une semaine (14 créneaux vides) */
        post: operations["WeeksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weeks/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Génère la semaine par tirage pondéré */
        post: operations["WeeksController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weeks/{id}/slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Met à jour un créneau (repas / portions) */
        patch: operations["WeeksController_updateSlot"];
        trace?: never;
    };
    "/weeks/{id}/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste de courses agrégée d’une semaine */
        get: operations["ShoppingListController_forWeek"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        Ingredient: {
            id: string;
            name: string;
            defaultUnit: string | null;
        };
        CreateIngredientDto: {
            name: string;
            defaultUnit?: string | null;
        };
        MealSummaryDto: {
            id: string;
            userId: string;
            name: string;
            rating: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            lastCookedAt: string | null;
            timesCooked: number;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedMealsDto: {
            items: components["schemas"]["MealSummaryDto"][];
            total: number;
            page: number;
            limit: number;
        };
        MealIngredientDto: {
            ingredientId: string;
            quantity: number;
            unit: string;
        };
        CreateMealDto: {
            name: string;
            rating?: number;
            isFavorite?: boolean;
            tags?: string[];
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        MealIngredient: {
            id: string;
            ingredient: components["schemas"]["Ingredient"];
            ingredientId: string;
            quantity: number;
            unit: string;
        };
        Meal: {
            id: string;
            name: string;
            rating: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            lastCookedAt: string | null;
            timesCooked: number;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            ingredients: components["schemas"]["MealIngredient"][];
        };
        UpdateMealDto: {
            name?: string;
            rating?: number;
            isFavorite?: boolean;
            tags?: string[];
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        WeekSlot: {
            id: string;
            date: string;
            /** @enum {string} */
            slot: "LUNCH" | "DINNER";
            mealId: string | null;
            meal: components["schemas"]["Meal"] | null;
            servings: number;
        };
        Week: {
            id: string;
            /** @description Lundi de la semaine (YYYY-MM-DD) */
            startDate: string;
            /** Format: date-time */
            createdAt: string;
            slots: components["schemas"]["WeekSlot"][];
        };
        CreateWeekDto: {
            /** @description Date calendaire dans la semaine voulue (YYYY-MM-DD) ; ramenée au lundi. Défaut : semaine courante. */
            startDate?: string;
        };
        UpdateSlotDto: {
            /** @description Repas à assigner, ou null pour vider le créneau */
            mealId?: string | null;
            servings?: number;
        };
        ShoppingListItemDto: {
            ingredientId: string;
            name: string;
            unit: string;
            quantity: number;
        };
        ShoppingListDto: {
            weekId: string;
            /** @description Lundi de la semaine (YYYY-MM-DD) */
            startDate: string;
            items: components["schemas"]["ShoppingListItemDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    IngredientsController_search: {
        parameters: {
            query?: {
                /** @description Filtre par nom (ILike) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    IngredientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    MealsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                favorite?: boolean;
                /** @description Filtre par tag exact */
                tag?: string;
                /** @description Filtre par nom (ILike) */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMealsDto"];
                };
            };
        };
    };
    MealsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMealDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MealsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    MealsController_markCooked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
        };
    };
    WeeksController_findCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Week"];
                };
            };
        };
    };
    WeeksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWeekDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Week"];
                };
            };
        };
    };
    WeeksController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Week"];
                };
            };
        };
    };
    WeeksController_updateSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                slotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSlotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Week"];
                };
            };
        };
    };
    ShoppingListController_forWeek: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
}
