/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check (process uniquement) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil de l’utilisateur courant */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Met à jour les préférences (jour de courses) */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée un compte et renvoie une paire de tokens */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifie un utilisateur */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renouvelle la paire de tokens */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recherche dans le catalogue d’ingrédients */
        get: operations["IngredientsController_search"];
        put?: never;
        /** Ajoute un ingrédient au catalogue (admin uniquement) */
        post: operations["IngredientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corrige le rayon ou l’unité par défaut d’un ingrédient (admin uniquement) */
        patch: operations["IngredientsController_update"];
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste paginée du catalogue de repas (filtres tag/name/incomplete) */
        get: operations["MealsController_findAll"];
        put?: never;
        /** Crée un repas (admin uniquement) */
        post: operations["MealsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tags existants, les plus utilisés en tête */
        get: operations["MealsController_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d’un repas (avec ingrédients) */
        get: operations["MealsController_findOne"];
        put?: never;
        post?: never;
        /** Supprime un repas (admin uniquement) */
        delete: operations["MealsController_remove"];
        options?: never;
        head?: never;
        /** Met à jour la recette (admin uniquement) */
        patch: operations["MealsController_update"];
        trace?: never;
    };
    "/meals/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Note du repas pour le compte appelant */
        patch: operations["MealsController_updateState"];
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan courant de l’utilisateur, créé vide au premier accès */
        get: operations["PlanController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remplit les créneaux vides par tirage pondéré */
        post: operations["PlanController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Met à jour un créneau (repas / portions) */
        patch: operations["PlanController_updateSlot"];
        trace?: never;
    };
    "/plan/slots/{slotId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déplace le contenu d’un créneau vers un autre, en l’échangeant si la cible est occupée */
        post: operations["PlanController_moveSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Vide les créneaux du plan et les items dérivés de la liste (les items manuels sont conservés) */
        delete: operations["PlanController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste de courses du plan, tenue à jour à chaque écriture sur le plan */
        get: operations["ShoppingListController_forPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalcule les items dérivés et ramène ceux supprimés à la main (coches conservées) */
        post: operations["ShoppingListController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ajoute un item manuel à la liste */
        post: operations["ShoppingListController_addItem"];
        /** Vide la liste, ou seulement les items cochés */
        delete: operations["ShoppingListController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/items/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supprime plusieurs items de la liste
         * @description POST et non DELETE : certains proxies ignorent le body d’un DELETE.
         */
        post: operations["ShoppingListController_removeItems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprime un item de la liste */
        delete: operations["ShoppingListController_removeItem"];
        options?: never;
        head?: never;
        /** Met à jour un item (checked, nom, quantité, unité) */
        patch: operations["ShoppingListController_updateItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeDto: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "USER" | "ADMIN";
            shoppingDay: number;
        };
        UpdateMeDto: {
            /** @description Jour de courses (0 = dimanche … 6 = samedi). */
            shoppingDay: number;
        };
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        TokenPairDto: {
            accessToken: string;
            refreshToken: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        Ingredient: {
            id: string;
            name: string;
            /** @enum {string|null} */
            defaultUnit: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c" | null;
            /** @enum {string|null} */
            aisle: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
        };
        CreateIngredientDto: {
            name: string;
            /** @enum {string|null} */
            defaultUnit?: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c" | null;
            /** @enum {string|null} */
            aisle?: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
        };
        UpdateIngredientDto: {
            /** @enum {string|null} */
            aisle?: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
            /** @enum {string|null} */
            defaultUnit?: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c" | null;
        };
        MealSummaryDto: {
            id: string;
            name: string;
            /** @description Compte propriétaire, null pour une recette de l’application. */
            userId: string | null;
            /** @enum {string} */
            status: "PRIVATE" | "PENDING" | "PUBLISHED";
            rating: number | null;
            tags: string[];
            /** @description 0 = repas à compléter, absent de la liste de courses. */
            ingredientCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedMealsDto: {
            items: components["schemas"]["MealSummaryDto"][];
            total: number;
            page: number;
            limit: number;
        };
        TagCountDto: {
            name: string;
            /** @description Nombre de repas qui portent ce tag. */
            count: number;
        };
        MealIngredientDto: {
            ingredientId: string;
            quantity: number;
            /** @enum {string} */
            unit: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c";
        };
        CreateMealDto: {
            name: string;
            /** @description Normalisés : minuscules, espaces réduits, doublons retirés. */
            tags?: string[];
            /** @description Procédé, astuces. Espaces de bord retirés ; une chaîne vide ou blanche vaut null. */
            description?: string | null;
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        MealIngredient: {
            id: string;
            ingredient: components["schemas"]["Ingredient"];
            ingredientId: string;
            quantity: number;
            /** @enum {string} */
            unit: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c";
        };
        MealDto: {
            id: string;
            name: string;
            /** @description Compte propriétaire, null pour une recette de l’application. */
            userId: string | null;
            /** @enum {string} */
            status: "PRIVATE" | "PENDING" | "PUBLISHED";
            rating: number | null;
            tags: string[];
            /** @description 0 = repas à compléter, absent de la liste de courses. */
            ingredientCount: number;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            ingredients: components["schemas"]["MealIngredient"][];
        };
        UpdateMealDto: {
            name?: string;
            /** @description Normalisés : minuscules, espaces réduits, doublons retirés. */
            tags?: string[];
            /** @description Procédé, astuces. Espaces de bord retirés ; une chaîne vide ou blanche vaut null. */
            description?: string | null;
            ingredients?: components["schemas"]["MealIngredientDto"][];
        };
        UpdateMealStateDto: {
            rating?: number | null;
        };
        PlanSlotDto: {
            id: string;
            /** @description Rang du jour dans le plan : 0 = premier jour. */
            dayIndex: number;
            /** @enum {string} */
            slot: "LUNCH" | "DINNER";
            mealId: string | null;
            meal: components["schemas"]["MealSummaryDto"] | null;
            servings: number;
            away: boolean;
        };
        PlanDto: {
            id: string;
            /** @description Premier jour du plan (YYYY-MM-DD). Ancre d’affichage : sert à libeller les jours et à situer le jour courant, jamais à retrouver un plan. */
            startDate: string;
            /** @description Nombre de jours couverts par le plan. */
            dayCount: number;
            /** Format: date-time */
            createdAt: string;
            slots: components["schemas"]["PlanSlotDto"][];
        };
        UpdateSlotDto: {
            /** @description Repas à assigner, ou null pour vider le créneau */
            mealId?: string | null;
            servings?: number;
            /** @description true vide le créneau et le marque « dehors » ; assigner un repas le retire. Incompatible avec un mealId non nul. */
            away?: boolean;
            /** @description Recopie le résultat du patch sur le créneau suivant (midi → soir, soir → midi du lendemain), en l’écrasant : le repas et les portions, ou l’état « dehors » (sans portions). 400 après le dernier dîner, ou si le créneau n’a ni repas ni état « dehors ». */
            alsoNext?: boolean;
        };
        MoveSlotDto: {
            /** @description Créneau de destination. Occupé, les deux créneaux échangent leur contenu. */
            targetSlotId: string;
        };
        ShoppingListItemDto: {
            id: string;
            /** @enum {string} */
            source: "DERIVED" | "MANUAL";
            ingredientId: string | null;
            name: string;
            unit: string | null;
            quantity: number | null;
            checked: boolean;
            /**
             * @description Celui de l’ingrédient pour un article issu des plats ; null = « Autre ».
             * @enum {string|null}
             */
            aisle: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
        };
        IncompleteMealDto: {
            id: string;
            name: string;
        };
        ShoppingListDto: {
            planId: string;
            /** @description Premier jour du plan (YYYY-MM-DD) */
            startDate: string;
            items: components["schemas"]["ShoppingListItemDto"][];
            /** @description Articles issus des plats que l’utilisateur a supprimés de la liste ; la synchro les ramène */
            dismissedCount: number;
            /** @description Repas planifiés sans ingrédient : la liste ne les couvre pas. */
            incompleteMeals: components["schemas"]["IncompleteMealDto"][];
            /** @description Ordre de parcours des rayons, celui du tri de `items`. */
            aisleOrder: ("PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER")[];
        };
        CreateShoppingListItemDto: {
            name: string;
            quantity?: number;
            /** @enum {string} */
            unit: "g" | "ml" | "pièce" | "tranche" | "gousse" | "feuille" | "boîte" | "rouleau" | "boule" | "c.à.s" | "c.à.c";
            /**
             * @description Rayon d’un article manuel. null = « Autre ».
             * @enum {string|null}
             */
            aisle?: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
        };
        RemoveShoppingListItemsDto: {
            /** @description Les ids hors de la liste de l’appelant sont ignorés. */
            itemIds: string[];
        };
        UpdateShoppingListItemDto: {
            checked?: boolean;
            name?: string;
            quantity?: number;
            unit?: string;
            /**
             * @description Rayon d’un article manuel. Sur un article issu des plats, 400 s’il diffère du rayon de son ingrédient.
             * @enum {string|null}
             */
            aisle?: "PRODUCE" | "BAKERY" | "MEAT_FISH" | "DAIRY" | "CHEESE_DELI" | "PANTRY_SAVORY" | "PANTRY_SWEET" | "FROZEN" | "DRINKS" | "HOUSEHOLD" | "OTHER" | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
        };
    };
    IngredientsController_search: {
        parameters: {
            query?: {
                /** @description Filtre par nom (ILike) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"][];
                };
            };
        };
    };
    IngredientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    IngredientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIngredientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
        };
    };
    MealsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description true = repas sans ingrédient */
                incomplete?: boolean;
                /** @description Filtre par tag, normalisé comme à l’écriture */
                tag?: string;
                /** @description Filtre par nom (ILike) */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMealsDto"];
                };
            };
        };
    };
    MealsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMealDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
        };
    };
    MealsController_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCountDto"][];
                };
            };
        };
    };
    MealsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
        };
    };
    MealsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MealsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
        };
    };
    MealsController_updateState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealStateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealDto"];
                };
            };
        };
    };
    PlanController_find: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_updateSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSlotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_moveSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveSlotDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    PlanController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDto"];
                };
            };
        };
    };
    ShoppingListController_forPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShoppingListItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItemDto"];
                };
            };
        };
    };
    ShoppingListController_clear: {
        parameters: {
            query: {
                scope: "all" | "checked";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_removeItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveShoppingListItemsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListDto"];
                };
            };
        };
    };
    ShoppingListController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShoppingListController_updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShoppingListItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItemDto"];
                };
            };
        };
    };
}
